apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperauth
  labels:
    app: hyperauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperauth
  template:
    metadata:
      labels:
        app: hyperauth
    spec:
      volumes:
        - name: ssl
          secret:
            secretName: hyperauth-https-secret
        - name: hyperauth-admin-token
          secret:
            secretName: hyperauth-admin-token
        - name: import-truststore # Enable If use External-oidc-provider or use mTLS (for initech)
          secret:
            secretName: external-oidc-provider-https-secret
            items:
              - path: truststore.p12
                key: truststore.p12
        - name: import-keystore # Enable If use External-oidc-provider or use mTLS (for initech)
          secret:
            secretName: external-oidc-provider-https-secret
            items:
              - path: keystore.p12
                key: keystore.p12
      containers:
        - name: hyperauth
          image: hyperregistry.tmaxcloud.org/hyperauth/hyperauth:b2.0.0.0
          args: ["start"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: passwords
                  key: DB_PASSWORD
            - name: KC_DB_PASSWORD
              value: "keycloak"
            - name: KC_DB_URL
              value: "jdbc:postgresql://192.168.9.194:31226/keycloak"
            - name: KC_LOG_LEVEL
              value: "INFO"
              # Below is for External-oidc-provider or use mTLS. (for initech)
              # If you use External-oidc-provider, you must set EXTERNAL_OIDC_PROVIDER_AUTH_URL, TOKEN_URL, PROFILE_URL
              # Or using mTLS with other idp, set truststore and keystore envs. (do not change trust/keystore filePath)
            - name: KC_SPI_TRUSTSTORE_FILE_FILE
              value: "/opt/keycloak/ssl/truststore.p12"
            - name: KC_SPI_TRUSTSTORE_FILE_TYPE
              value: "PKCS12"
            - name: KC_SPI_TRUSTSTORE_FILE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: external-truststore-password
                  key: password
            - name: KC_HTTPS_KEY_STORE_FILE
              value: "/opt/keycloak/ssl/keystore.p12"
            - name: KC_HTTPS_KEY_STORE_PASSWORD
              value: "tmax@23"
            - name: EXTERNAL_OIDC_PROVIDER_AUTH_URL
              value: "https://tmax.sso.initech.com/externalauth"
            - name: EXTERNAL_OIDC_PROVIDER_TOKEN_URL
              value: "https://tmax.sso.initech.com/token"
            - name: EXTERNAL_OIDC_PROVIDER_PROFILE_URL
              value: "https://tmax.sso.initech.com/user"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
          volumeMounts:
            - name: ssl
              mountPath: /etc/x509/https
            - name: hyperauth-admin-token
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            # Enable belows if use External-oidc-provider or use mTLS (for initech)
            - name: import-truststore
              mountPath: /opt/keycloak/ssl/truststore.p12
              subPath: truststore.p12
            - name: import-keystore
              mountPath: /opt/keycloak/ssl/keystore.p12
              subPath: keystore.p12
